name: Extra-task

on: 
    push:
        branches:
            - master

env:
    DEPLOY_VER: ${{ github.sha }}
    MONTH: "February"
    DAY_OF_THE_MONTH: "15"
    YEAR: 1997
    FAVORITE_DAY_OF_WEEK: ${{ secrets.FAVORITE_DAY_OF_WEEK }}


jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Print entity of repo
          run: ls
        - name: Print entity of log.txt
          run: cat log.txt
        - name: Print DEPLOY_VER
          run: echo "Hello from $DEPLOY_VER commit"
    
    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Print day of the month
          run: echo $DAY_OF_THE_MONTH
        - name: Print system date and time
          run: date
        - name: Print variable
          run: echo "Day - $DAY_OF_THE_MONTH\nMonth - $MONTH\nYaer - $YEAR"
        - name: Print favorite day of week
          run: echo "My favorite day of week is $FAVORITE_DAY_OF_WEEK"
        - name: Reason why we get ***
          run: echo "To hide any sensitive data we can use secrets they are encrypted. Secrets will not be printed during execution."
